name: Deploy DinnerPartiesOfNY (frontend -> GitHub Pages)

on:
  push:
    branches: [ main ]


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Prepare install (force npm + pin compatible deps)
        working-directory: frontend
        shell: bash
        run: |
          set -e
          # always use npm in CI
          if [ -f yarn.lock ]; then rm -f yarn.lock; fi
          npm config set legacy-peer-deps true

          # react-day-picker@8 requires date-fns ^2 or ^3 (not v4)
          npm pkg set "dependencies.date-fns=3.6.0"

          # CRA v5 expects ESLint 8.x
          npm pkg set "devDependencies.eslint=8.57.1"
          npm pkg set "devDependencies.@eslint/js=8.57.1"

          # Webpack/terser toolchain wants Ajv v8 + ajv-keywords v5
          npm pkg set "devDependencies.ajv=^8"
          npm pkg set "devDependencies.ajv-keywords=^5"

      - name: Install dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Build site (CRA/CRACO)
        working-directory: frontend
        env:
          PUBLIC_URL: .
          CI: false
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
